# Generated by Django 6.0 on 2025-12-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
